version: "3"

services:
  app:
    container_name: trainit-backend
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/srv/app/src/
      - ./build:/srv/app/build
      - ./data:/srv/app/data
    expose:
      - '8080'
      - '9229'
      - '9099'
    ports:
      - "8080:8080"
      - "9229:9229"
