version: "3"

services:
  app:
    container_name: trainit-backend
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./data:/srv/app/data
      - /etc/letsencrypt/:/etc/letsencrypt/
    network_mode: host